### ISSUE TITLE
Debug Submission Week in Photography Index

### ISSUE THREAD

**Issue by cainaru** [EWB/engagingthenorthcountry#4]

**Comment by cainaru** [comment]
When setting the pager in the View to Display All Items, all of the Weeks show. Continuing to investigate this.

**Comment by cainaru** [comment]
It also looks like the same thing is happening with the Organizations.

**Comment by EWB** [comment]
What happens if you change to no pager/show all?

**Comment by cainaru** [comment]
All Organizations show in the filter as well as all Submission Weeks.

**Comment by cainaru** [comment]
It also looks like it is caused by MixItUp, not Better Exposed Filters.

**Comment by EWB** [comment]
OK, thanks - I switched the view to show all - with no pager - let's keep it at that and call this closed for now. thanks for checking into it.
